### ISSUE TITLE
csv書き込みに失敗する

### ISSUE THREAD

**Issue by brantechs** [ri-riri/sotu#1]
```
with open("new評価ワード(係り受け済).csv", "w", newline="")as fp:# newline=""はcsvファイルの一行詰めるため
    writer = csv.writer(fp)
    hyokaword_kakariuke_lst = []
    for element in response["result"]["chunks"]:
        hyokaword_kakariuke_lst.append(element["tokens"])
        hyokaword_kakariuke_lst.append(element["id"])
        hyokaword_kakariuke_lst.append(element["head"])
    print(hyokaword_kakariuke_lst)
    writer.writerows(hyokaword_kakariuke_lst)   #ここで　Error: iterable expected, not int
```

`print(hyokaword_kakariuke_lst)`の結果の一部を以下に例示する．
```
[
 [
  ['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*'], 
  ['らしい', 'らしい', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本形']
 ], 0, 1,
 [
  ['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*'], 
  ['らしく', 'らしく', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本連用形'],
  ['ない', 'ない', 'ない', '接尾辞', '形容詞性述語接尾辞', 'イ形容詞アウオ段', '基本形']
 ], 1, 7,
 [
  ['ニコン', 'にこん', 'ニコン', '名詞', '組織名', '*', '*'],
  ['らしい', 'らしい', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本形']
 ], 2, 7
...
]
```

**Comment by brantechs** [comment]
print内容を見やすいように整形しましたが，そもそもこの形式のリストが出力されるのは期待通りですか？
私としてはこうあるべきだと思うのですが．．
```
[
 ['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*', 0, 1], 
 ['らしい', 'らしい', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本形', 1, 4]
...
]
```

1. リストに格納すべき値はなにか
2.  その値はどのように取り出せるか（元データのどこに格納されているか）
を整理して，`hyokaword_kakariuke_lst`の形式を更新してみよう！

#####15:30追記
`Error: iterable expected, not int`に関しては，以前紹介した通りイテラブルオブジェクトではなくintが現れたので書き込めないよ，という内容なので， "0, 1,"や"1, 7,"のような部分の仕様を変更すれば解消されます．

**Comment by ri-riri** [comment]
やってみたのですが分からないので、もう少しヒント下さい！

**Comment by brantechs** [comment]
![https://developer.yahoo.co.jp/webapi/jlp/da/v2/parse.html](https://user-images.githubusercontent.com/32893025/93312986-d5fed880-f842-11ea-8d68-7d5fd7836140.png)これを見る限り，headが修飾先の文節番号，idがその文節の番号っていうことみたいやな．
とりあえずは`element["tokens"]`の要素の中に`element["id"]`と`element["head"]`の両方を書き込んでおいたらどうかな？下の期待値ではtokensの最後に二つ付け足す形にしています．（同じ文節の中では`element["id"]`と`element["head"]`は同じ値になるはず）

```
[
 [
  ['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*',  0, 1], 
  ['らしい', 'らしい', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本形', 0, 1]
 ], 
 [
  ['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*',  1, 7], 
  ['らしく', 'らしく', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本連用形', 1, 7],
  ['ない', 'ない', 'ない', '接尾辞', '形容詞性述語接尾辞', 'イ形容詞アウオ段', '基本形', 1, 7]
 ],
 [
  ['ニコン', 'にこん', 'ニコン', '名詞', '組織名', '*', '*', 2, 7],
  ['らしい', 'らしい', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本形', 2, 7]
 ],
...
]
```

**Comment by ri-riri** [comment]
for element in response["result"]["chunks"]:
        element["tokens"].append(element["id"])
        element["tokens"].append(element["head"])
        hyokaword_kakariuke_lst.append(element["tokens"])
        #hyokaword_kakariuke_lst.append(element["id"])
        #hyokaword_kakariuke_lst.append(element["head"])
    print(hyokaword_kakariuke_lst)

**Comment by ri-riri** [comment]
こうしたのですが何かが違います！

**Comment by brantechs** [comment]
違うと思うときは出力結果と，どういう感じにしたいかとかがあると答えやすいかな！

**Comment by ri-riri** [comment]
[[['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*'], ['らしい', 'らしい', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本形'], 0, 1], [['キヤノン', 'きやのん', 'キヤノン', '名詞', '組織名', '*', '*'], ['らしく', 'らしく', 'らしい', '助動詞', '*', 'イ形容詞イ段', '基本連用形'],

**Comment by ri-riri** [comment]
出力結果がこんな感じなのですが、キャノンの後に0，1がはいっていないのと、[ ]のなかに０，１を入れれないです！

**Comment by brantechs** [comment]
ふはは
element["tokens"]の中には一つ以上複数の要素があるから，繰り返しでappendしていかなアカン．forで回そう．

**Comment by ri-riri** [comment]
やってみます！

**Comment by brantechs** [comment]
一旦Close．
同様の問題が発生したら再度Openか，別issueで登録する．
