### ISSUE TITLE
2次元リスト作成

### ISSUE THREAD

**Issue by ri-riri** [ri-riri/sotu#2]

**Comment by ri-riri** [comment]
df1 = pd.read_excel("new評価ワード.xlsx", sheet_name=0)
df1.to_csv("new評価ワード.csv", index=False, header=None, encoding='utf_8_sig')
with open("new評価ワード.csv", encoding='utf_8_sig') as fp:
    one_lst = []
    reader = csv.reader(fp)
    for row in reader:
        one_lst.append(row)#A列
    #one_lst.remove(",")
    print(one_lst)``

**Comment by ri-riri** [comment]
二次元リストはできたのですが、出力結果に','が入ってしまいます！
one_lst.remove（", "）などをしてみたのですが無理でした！','を消したいです

**Comment by ri-riri** [comment]
df1 = pd.read_excel("new評価ワード.xlsx", sheet_name=0)
df1.to_csv("new評価ワード.csv", index=False, header=None, encoding='utf_8_sig')
with open("new評価ワード.csv", encoding='utf_8_sig') as fp:
    one_lst = []
    reader = csv.reader(fp)
    for row in reader:
        one_lst.append(row)#A列
    #one_lst.remove(",")
    print(one_lst)

**Comment by ri-riri** [comment]
[['キヤノンらしい', 'キャノンらしい', 'キャノンらしく', 'キヤノンらしさ', 'キャノンっぽい', 'キヤノンぽい', 'Canonらしい', 'Canonらしく', 'canonらしさ', '', ''], ['キヤノンらしくない', '', '', '', '', '', '', '', '', '', ''],

**Comment by ri-riri** [comment]
間違えました！　” ”でした！

**Comment by brantechs** [comment]
@ri-riri 
どうやらこれはcsv readerの仕様のようなので，読み込まないようにするのはあきらめましょう．
代わりにですが，読み込み後に空白要素を除外するような処理をかけて対応しましょう．
[こちら](https://qiita.com/github-nakasho/items/a08e21e80cbc9761db2f)が参考になるでしょう．
二次元リストであることに注意して，処理を考えてみてください．

**Comment by ri-riri** [comment]
list.remove(x): x not in list

このエラーが出るのですがこれは何でしょうか？

**Comment by brantechs** [comment]
listのなかにないものをremoveしようとして怒られています（英語を頑張りましょう）
恐らく，”キャノンらしい”のリストには空白要素がないことが原因です．
これを回避するには　"python 例外処理"　あたりで検索して解決策を模索してみてください．
