### ISSUE TITLE
保存したtextを読み込む

### ISSUE THREAD

**Issue by ri-riri** [ri-riri/sotu#3]

**Comment by ri-riri** [comment]
for camera in cameras:
    for page in range(1,cameras[camera][1]+1): #range(1,4)は1,2,3なので＋1をする
        for person,item in enumerate(wordclass,1): #for i, name in enumerate(l, 1):  print(i, name)  1 Alice  2 Bob  3 Charlie　　
            file = open("./review/{0}_{1}_{2}.txt".format(camera,str(page),person), "r", encoding = 'cp932', errors = 'ignore')
            review = file.read()
            print(review)
            file.close()

**Comment by ri-riri** [comment]
このようにして保存したレビューを読み込んだのですが、明らかに保存した量よりも少ないのですが、どこがおかしいのわかりません！

**Comment by ri-riri** [comment]
このようにして保存したレビューを読みこんだのですが、明らかに保存した量よりも少ないのですが、どこがおかしいのわかりません！

**Comment by ri-riri** [comment]
for camera in cameras:
    for page in range(1,cameras[camera][1]+1): #range(1,4)は1,2,3なので＋1をする
        r = requests.get("https://review.kakaku.com/review/{0}/page={1}/#tab".format(cameras[camera][0],str(page))) #requestを使ってurlを呼び出す parserでrを分析  {0}{1}はformatの何番目にその要素があるか
        soup = BeautifulSoup(r.content, "html.parser") #BeautifulSoupのアルゴリズムを使う
        wordclass = soup.find_all("p","revEntryCont") #pでくくられたrevEntryCont（レビュー本文）を全部探す
        for person,item in enumerate(wordclass,1): #for i, name in enumerate(l, 1):  print(i, name)  1 Alice  2 Bob  3 Charlie　　
            file = open("./review/{0}_{1}_{2}.txt".format(camera,str(page),person), "r")
            review = file.read()
            print(review)
            file.close()

**Comment by ri-riri** [comment]
できました！

**Comment by brantechs** [comment]
返事遅れて申し訳ない．

問題なさそうですね．
解決したチケットはどんどんCloseしていきましょう，作成者のみがCloseできます．
